ProjectK/Assets/Prefabs/BulletPrefab.prefab, ProjectK/Assets/Prefabs/BulletPrefab.prefab.meta, ProjectK/Assets/Scripts/Gun/Bullet.cs, ProjectK/Assets/Scripts/Gun/Bullet.cs.meta
1. 빈 오브젝트 생성, 자식으로 캡슐 오브젝트 추가, 각도 수정
2. Bullet 스크립트 추가
3. Move, LifeTime 구현
=> [Add] 총알 프리팹 구현

ProjectK/Assets/Animations.meta, ProjectK/Assets/Animations/Player.meta, ProjectK/Assets/Animations/Player/PLayer_Reload.anim, ProjectK/Assets/Animations/Player/PLayer_Reload.anim.meta, ProjectK/Assets/Animations/Player/PlayerAnimationController.controller, ProjectK/Assets/Animations/Player/PlayerAnimationController.controller.meta, ProjectK/Assets/Animations/Player/Player_Attack.anim, ProjectK/Assets/Animations/Player/Player_Attack.anim.meta, ProjectK/Assets/Animations/Player/Player_Die.anim, ProjectK/Assets/Animations/Player/Player_Die.anim.meta, ProjectK/Assets/Animations/Player/Player_Idle.anim, ProjectK/Assets/Animations/Player/Player_Idle.anim.meta, ProjectK/Assets/Animations/Player/Player_Run.anim, ProjectK/Assets/Animations/Player/Player_Run.anim.meta, ProjectK/Assets/Scenes/GH.unity, ProjectK/Assets/Scripts/Player/PlayerAnimation.cs, ProjectK/Assets/Scripts/Player/PlayerAnimation.cs.meta, ProjectK/Assets/Scripts/Player/PlayerController.cs
PlayerAnimation
1. 애니메이터 프로퍼티 값 변경
2. 애니메이션 상태에 대한 판단
PlayerController
1. 플레이어 상태(enum) 추가
2. 플레이어의 현재 상태 제어
플레이어 프리팹
1. 플레이어 애니메이션 스크립트 추가
애니메이션 폴더에 애니메이션 추가, 애니메이터 추가
애니메이터 파라미터 추가
=> [Add] 플레이어 애니메이션 연결

ProjectK/Assets/Scripts/Gun/Gun.cs
1. 관련 변수 추가
2. Fire - 연사 대기 진입
3. Reload - 장전 타임 진입
4. Update에서 장전시간, 연사시간 감산
=> [Add] 총 리로드, 연사속도 구현

ProjectK/Assets/Prefabs/PlayerConnect.prefab, ProjectK/Assets/Prefabs/PlayerConnect.prefab.meta, ProjectK/Assets/Scenes/JK.unity, ProjectK/Assets/Scripts/Gun/Bullet.cs, ProjectK/Assets/Scripts/Gun/Gun.cs, ProjectK/Assets/Scripts/Player/PlayerController.cs
1. 플레이어 스크립트에서 Gun 변수 추가
2. inputFire에 Gun Fire 호출
3. inputReload에 Gun Reload 호출
4. Gun.cs Fire에서 총알 Bullet 생성
5. Bullet.SetDirection 호출
6. 플레이어 프리팹에 총 오브젝트 추가
=> [Add] 총알 발사 기능 연결

ProjectK/Assets/Prefabs/Player.prefab, ProjectK/Assets/Prefabs/PlayerConnect.prefab, ProjectK/Assets/Scenes/YT.unity, ProjectK/Assets/Scripts/Player/PlayerController.cs
PlayerController.cs
-Update()
--RotateCharacterOnMousePosition
void RotateCharacterOnMousePosition()
// 마우스와 메인 카메라를 이용하여 마우스 포인터의 월드 좌표를 계산하여 플레이어 캐릭터를 회전합니다.
https://github.com/user-attachments/assets/6378a99b-317e-4872-b350-f2aeb3a965ce
=> [Feature] 플레이어 회전 기능 추가

ProjectK/Assets/Prefabs/PlayerConnect.prefab, ProjectK/Assets/Scripts/Camerafollow.cs, ProjectK/Assets/Scripts/Camerafollow.cs.meta
1. 카메라 팔로우 cs 추가
2. 플레이어 프리팹에 컴포넌트 추가
3. 메인카메라의 offSet을 저장, 플레이어 위치에 오프셋 더해서 카메라 위치 결정
=> [Add] 카메라가 플레이어 추적

ProjectK/Assets/Prefabs/PlayerUI.prefab, ProjectK/Assets/Prefabs/PlayerUI.prefab.meta, ProjectK/Assets/Scenes/GH.unity, ProjectK/Assets/Scripts/PlayerUI.meta, ProjectK/Assets/Scripts/PlayerUI/PlayerUIManager.cs, ProjectK/Assets/Scripts/PlayerUI/PlayerUIManager.cs.meta
1. PlayerUI 폴더 생성
2. PlayerUIManager.cs 생성
2.1 크로스 헤어 이미지가 마우스 포인터 위치를 추적
3. PlayerUI 캔버스 오브젝트 프리팹 생성
=> [Add] UI추가 크로스헤어

ProjectK/Assets/Prefabs/@MasterData.prefab, ProjectK/Assets/Prefabs/@MasterData.prefab.meta, ProjectK/Assets/Prefabs/PlayerConnect.prefab, ProjectK/Assets/Scripts/ItemBase.cs, ProjectK/Assets/Scripts/ItemBase.cs.meta, ProjectK/Assets/Scripts/MasterDataManager.cs, ProjectK/Assets/Scripts/MasterDataManager.cs.meta, ProjectK/Assets/Scripts/Player/PlayerInventory.cs, ProjectK/Assets/Scripts/Player/PlayerInventory.cs.meta
1. 아이템 클래스 구현
2. 마스터 데이터 매니저 구현
- 원본 아이템 데이터 관리
3. 캐릭터 인벤토리 구현
- 1. 총기 인벤토리, 소비 인벤토리 구별
- 2. 각 인벤토리에 들어갈 아이템 타입 fixType 배열로 정의
- 3. 아이템 습득 구현
- 장착아이템인 경우
- 소비아이템인 경우
4. 캐릭터 프리팹에 인벤토리 컴포넌트 추가
5. 마스터 데이터 프리팹 추가
=> [Feature] 아이템 클래스와 캐릭터 인벤토리 구현

ProjectK/Assets/Scripts/Gun/Gun.cs, ProjectK/Assets/Scripts/Player/PlayerInventory.cs
Gun.cs
1. 장착, 탈착 함수 추가
- 아이템에 따라 타겟 스텟 변동
2. 초당 발사 변수 defaultRps 추가
- 초당 발사 숫자에 따라 연사속도 계산
CharactorInventory.cs
1. 장비 아이템 습득시 기존 장비 Detach, 새 장비 Attach 호출
=> 52 총기 부착물과 스탯 연동

ProjectK/Assets/Scripts/Gun/Gun.cs, ProjectK/Assets/Scripts/Player/PlayerInventory.cs
1. 인벤토리에서 Gun을 참조하던 구조 제거
2. 인벤토리에서는 GunItem 보유만 관리
3. Gun에서는 GunItem[] 을 받아 스텟 재계산 수행
- 해당 함수는 컨트롤러에서 호출 예정
=> [Update] 52 총기 부착물과 스탯 연동 

ProjectK/Assets/Scripts/Player/PlayerInventory.cs
=> [Fix] #58 Issue 버그 픽스

ProjectK/Assets/Prefabs/DropBox.prefab, ProjectK/Assets/Prefabs/DropBox.prefab.meta, ProjectK/Assets/Scripts/DropBox.meta, ProjectK/Assets/Scripts/DropBox/DropBox.cs, ProjectK/Assets/Scripts/DropBox/DropBox.cs.meta, ProjectK/Assets/Scripts/DropBox/DropBoxTable.cs, ProjectK/Assets/Scripts/DropBox/DropBoxTable.cs.meta, ProjectK/Assets/Scripts/MasterDataManager.cs
1. 드롭박스 뽑기용 테이블 세팅
2. 드롭박스 구현
- 1. DropBox. cs 추가
- 2. 시작시 DiceItem 호출
- - 최대 maxRoll 횟수 만큼 뽑기 진행, 뽑기 성공시 haveItem에 추가
- 3. 상자 열고, 닫고, 아이템 골랐을때 이벤트 호출
3. 드롭박스 프리팹 추가
=> 62 드롭박스 인벤토리 구현

ProjectK/Assets/Scenes/GH.unity, ProjectK/Assets/Scripts/UI/SystemUI/SystemUIManager.cs
1. float형을 int 형으로 변환하여 출력하는 것으로 수정
=> [Fix] 시스템 UI 플레이 타임 표기 수치 버그 수정

ProjectK/Assets/Prefabs/DropBox_ItemSlot1.prefab, ProjectK/Assets/Prefabs/DropBox_ItemSlot1.prefab.meta, ProjectK/Assets/Prefabs/PlayerUI.prefab, ProjectK/Assets/Scenes/GH.unity, ProjectK/Assets/Scripts/UI/PlayerUI/PlayerUIManager.cs
- 드롭박스 UI 배치
- 드롭박스 슬롯 버튼과 상호작용
- 드롭박스 패널 온오프
1. PlayerUI 오브젝트에 DropBoxPanel 추가
2. DropBox_ItemSlot1 프리펩 추가 및 배치
3. PlayerUI 프리팹 수정
4. 각 버튼에 이벤트 리스너를 등록해서 각 버튼의 정보를 가져오는 코드 추가
5. Crosshair 이미지 Raycast Target 비활성화
6. dropBoxPanel이 활성화 비활성화 되는 함수 추가
https://github.com/user-attachments/assets/4c10306d-b853-4a3f-972e-4e88d8eeee61
=> [Add] 드롭박스 인벤토리 PopUp UI 배치

ProjectK/Assets/Prefabs/Effect.meta, ProjectK/Assets/Prefabs/Effect/EffectSpawner.prefab, ProjectK/Assets/Prefabs/Effect/EffectSpawner.prefab.meta, ProjectK/Assets/Prefabs/Effect/bloodEffect.prefab, ProjectK/Assets/Prefabs/Effect/bloodEffect.prefab.meta, ProjectK/Assets/Scripts/Effect.meta, ProjectK/Assets/Scripts/Effect/EffectObject.cs, ProjectK/Assets/Scripts/Effect/EffectObject.cs.meta, ProjectK/Assets/Scripts/Effect/EffectSpawner.cs, ProjectK/Assets/Scripts/Effect/EffectSpawner.cs.meta
1. EffectSpawner.cs , EffectObject.cs 추가
* 이펙트오브젝트 cs
- 파티클 오브젝트
- 라이프 시간이 끝나면 오브젝트를 비활성화하고 SpawnerPool로 돌아간다
* 이펙트 스포너
- 이펙트 오브젝트를 3개 생성
- 중첩방지를 위한 타이머 진행
- 이펙트 플레이 호출을 받으면 이펙트 오브젝트 플레이
2. 프리팹 추가
=> 50 피격 이펙트 생성

ProjectK/Assets/Materials.meta, ProjectK/Assets/Materials/StencilFilter.mat, ProjectK/Assets/Materials/StencilFilter.mat.meta, ProjectK/Assets/Materials/StencilMask.mat, ProjectK/Assets/Materials/StencilMask.mat.meta, ProjectK/Assets/Prefabs/InputManager.prefab, ProjectK/Assets/Scenes/YT.unity, ProjectK/Assets/Scripts/InputManager/InputManager.cs, ProjectK/Assets/Scripts/Player/PlayerController.cs, ProjectK/Assets/Scripts/Player/PlayerMove.cs, ProjectK/Assets/Scripts/Player/PlayerSight.cs, ProjectK/Assets/Scripts/Player/PlayerSight.cs.meta, ProjectK/Assets/Scripts/UI/PlayerUI/PlayerUIManager.cs, ProjectK/Assets/Scripts/World.meta, ProjectK/Assets/Scripts/World/FogOverlayGenerator.cs, ProjectK/Assets/Scripts/World/FogOverlayGenerator.cs.meta, ProjectK/Assets/Shader.meta, ProjectK/Assets/Shader/StencilFilter.shader, ProjectK/Assets/Shader/StencilFilter.shader.meta, ProjectK/Assets/Shader/StencilMask.shader, ProjectK/Assets/Shader/StencilMask.shader.meta
1. PlayerController RotateCharcterOnMousePosition()
->
PlayerMove
Rotate()
2. PlayerController [Add] GetMouseWorldPosition
3. PlayerSight 시야각을 구현하는 스크립트
4. FogOverlay 전장의 안개 역할을 하는 프리펩
=> [Add] 플레이어 시야각 구현

ProjectK/Assets/Scripts/ItemBase.cs, ProjectK/Assets/Scripts/MasterDataManager.cs, ProjectK/Assets/fileData.csv, ProjectK/Assets/fileData.csv.meta
1. 마스터데이터매니저에서 csv 파싱 후 ItemBase 생성
=> 75 csv 기반 아이템 데이터 파싱 시스템 개발

ProjectK/Assets/Prefabs/DropBox_ItemSlot1.prefab, ProjectK/Assets/Scripts/DropBox/DropBoxTable.cs, ProjectK/Assets/Scripts/UI/PlayerUI/DropBoxSlot.cs, ProjectK/Assets/Scripts/UI/PlayerUI/DropBoxSlot.cs.meta, ProjectK/Assets/Scripts/UI/PlayerUI/PlayerUIManager.cs
1. 드롭박스 cs
- 플레이어로부터 OpenBox()호출 받으면 Open 이벤트 호출
2. DropBox Slot.cs , 프리팹 추가
2. PlayerUI매니저
- 드롭박스슬롯들 GetComponets
- 상자 열면 패널 켜고 열린 상자의 아이템 리스트 가지고 슬롯 표기
- 상자 닫히면 패널 끄기
- 열기,닫기 함수를 드롭박스 이벤트 함수에 연결
=> 78 드롭박스UI 아이템 표기

ProjectK/Assets/Prefabs/BulletPrefab.prefab, ProjectK/Assets/Prefabs/PlayerUI.prefab, ProjectK/Assets/Scripts/DropBox/DropBox.cs, ProjectK/Assets/Scripts/Gun/Bullet.cs, ProjectK/Assets/Scripts/Gun/Gun.cs, ProjectK/Assets/Scripts/UI/PlayerUI/PlayerUIManager.cs
1. 플레이어 UI 프리팹 에 탄창 텍스트 추가
2. PlayerUIManager.cs UpdateCrosshairUISize 함수 추가 및 이벤트 등록
3. PlayerUIManager.cs UpdateAmmoUI함수 추가 및 이벤트 등록
4. Gun.cs OnChageAmmoUI 이벤트 추가
5. Bullet.cs 총알 충돌시 Destroy 추가
6. 총알 프리팹 사이즈 조정
[[Fix] 충돌 해결]
1. 리뷰는 정균님에게
https://github.com/user-attachments/assets/7da402ea-367c-4154-bde9-9cac6ff683e9
=> [Feature] 크로스헤어 크기 변경

ProjectK/Assets/Prefabs/PlayerConnect.prefab, ProjectK/Assets/Scripts/DropBox/DropBox.cs, ProjectK/Assets/Scripts/Player/BoxDetector.cs, ProjectK/Assets/Scripts/Player/BoxDetector.cs.meta, ProjectK/Assets/Scripts/Player/PlayerController.cs
1. 박스 디텍터 추가
- 근처 박스 탐색
- 가장 가까운 박스 반환
2. 캐릭터 프리팹에 박스 디텍터 추가
3. 박스랑 상호 작용으로 박스 Open
- 매개변수로 아이템픽 콜백함수 전달
=> 49 플레이어 아이템 획득 처리

ProjectK/Assets/Prefabs/PlayerConnect.prefab, ProjectK/Assets/Scripts/Player/PlayerController.cs
1. 애니메이터 할당
2. Sight 컴포넌트 추가
3. 탐색 컬라이더 IsTrigger
=> [Feature] 캐릭터 프리팹 수정

ProjectK/Assets/DefaultNetworkPrefabs.asset, ProjectK/Assets/Prefabs/@NetworkManager.prefab, ProjectK/Assets/Prefabs/PlayerNetwork.prefab, ProjectK/Assets/Prefabs/PlayerNetwork.prefab.meta
1. 네트워크 매니저에 기본 캐릭터로 등록
2. 네트워크 오브젝트 리스트에 등록
=> [Add] 네트워크용 플레이어 프리팹 추가

ProjectK/Assets/Prefabs/PlayerNetwork.prefab, ProjectK/Assets/Scripts/GameManager/GameManager.cs, ProjectK/Assets/Scripts/Player/PlayerController.cs, ProjectK/ProjectSettings/ProjectSettings.asset
[Add] 싱글, 멀티 코드 분리 위해서 MULTI 심볼 생성
[Fix] Scene Migration Sync 옵션 활성화
[Update] 조종자 등록시 bool 값 받음
[Update] 플레이어 컨트롤러 넷코드화
=> 102 net2 inputmanager 로컬 전용 처리 분리

ProjectK/Assets/Scripts/Camerafollow.cs
=> [Feature] 카메라팔로우에 IsOwner 체크

ProjectK/Assets/Prefabs/UI/SystemUI.prefab, ProjectK/Assets/Scenes/YT.unity, ProjectK/Assets/Scripts/UI/SystemUI/SystemUIManager.cs, ProjectK/ProjectSettings/Packages/com.unity.multiplayer.tools/CustomColorSettings.asset, ProjectK/ProjectSettings/VirtualProjectsConfig.json
=> [Feature] SystemUI에 패널 추가

ProjectK/Assets/Scenes/YT.unity, ProjectK/Assets/Scripts/GameManager/GameManager.cs, ProjectK/Assets/Scripts/InputManager/InputManager.cs, ProjectK/Assets/Scripts/Player/PlayerController.cs, ProjectK/Assets/Scripts/UI/InGameUI/InGameUIManager.cs, ProjectK/Assets/Scripts/UI/PlayerUI/PlayerUIManager.cs, ProjectK/Assets/Scripts/UI/SystemUI/SystemUIManager.cs, ProjectK/ProjectSettings/EditorBuildSettings.asset, ProjectK/ProjectSettings/ProjectSettings.asset
게임 종료 시퀀스 발생시 SystemUI 에 결과 반영
2. 10초 뒤 게임 상태 Ready로 초기화
=> [Feature] 게임 종료 시퀀스 UI에 반영

ProjectK/Assets/Prefabs/PlayerNetwork.prefab
=> 105 net4 위치 동기화 networktransform 적용

ProjectK/Assets/DefaultNetworkPrefabs.asset, ProjectK/Assets/Prefabs/NetworkBulletPrefab.prefab, ProjectK/Assets/Prefabs/NetworkBulletPrefab.prefab.meta, ProjectK/Assets/Prefabs/PlayerNetwork.prefab, ProjectK/Assets/Scripts/Gun/Bullet.cs, ProjectK/Assets/Scripts/Gun/Gun.cs
1. 총알 프리팹 복사
- 네트워크 오브젝트 추가
- 네트워크 트랜스폼 추가
2. 네트워크 플레이어의 총이 쏠 프리팹에 네트워크 총알 추가
3. 네트워크 오브젝트 리스트에 총알 추가
4. 총알 네트워크 스폰 
- 1. 클라이언트에서 총알 발사 ServerRpc로 요청
- Server에서 네트워크 총알 프리팹 생성
5. 총알 속도, 연사속도 수정
=> 110 net7 총알 생성이동 서버 권한 처리

ProjectK/Assets/Scenes/MainScene.unity, ProjectK/Assets/Scripts/Player/PlayerController.cs
크로스헤어 이미지 스프라이트 교체
https://github.com/user-attachments/assets/68cd53e2-7657-4802-8b83-2c56a00c37a4
=> [Feature] 크로스 헤어 이미지 교체

ProjectK/Assets/Scripts/Player/PlayerSight.cs
카메라 포지션 0, 40, 0으로 고정
회전 75, 0, 0고정
플레이어 기본 시야 거리 15로 확장
화면 해상도는 FHD고정
=> [Update] 메인씬 구성 세부 조정

ProjectK/Assets/DefaultNetworkPrefabs.asset, ProjectK/Assets/Prefabs/UI/SystemUI.prefab, ProjectK/Assets/Scenes/JH.unity, ProjectK/Assets/Scripts/UI/SystemUI/SystemUIManager.cs
사망 UI 패널 + Text
+ System Manager 추가구현
리.뷰
=> [Update]사망UI 패널

ProjectK/Assets/Scripts/UI/SystemUI/SystemUIManager.cs
=> [Fix][Header("DidUI")]오타수정

ProjectK/Assets/Prefabs/Deployables item.meta, ProjectK/Assets/Prefabs/Deployables item/WoodenBox.prefab, ProjectK/Assets/Prefabs/Deployables item/WoodenBox.prefab.meta, ProjectK/Assets/Scenes/JH.unity
prefab -> Deployables item - > 바리케이트 형식의 설치형 나무박스 prefab 1개  추가
=> [Add] 설치형 나무박스 prefab 추가

ProjectK/Assets/Scenes/JK.unity, ProjectK/Assets/Scripts/GameManager/GameManager.cs, ProjectK/Assets/Scripts/GameManager/SpawnAssginer.cs, ProjectK/Assets/Scripts/GameManager/SpawnAssginer.cs.meta, ProjectK/Assets/Scripts/Player/PlayerController.cs
1. 트랜스폼 랜덤하게 섞는 클래스 AssingSpawner.cs 추가
2. GameManager에서 게임 시작할때 스포너 클래스에서 위치 가져옴
- 가져온 위치 순서대로 플레이어 위치 배정
=> 121 플레이어 스폰 위치 설정 및 적용

ProjectK/Assets/DefaultNetworkPrefabs.asset, ProjectK/Assets/Prefabs/DropBox.prefab, ProjectK/Assets/Prefabs/GameManager.prefab, ProjectK/Assets/Scenes/JK.unity, ProjectK/Assets/Scripts/DropBox/DropBox.cs, ProjectK/Assets/Scripts/GameManager/GameManager.cs, ProjectK/Assets/Scripts/Player/PlayerController.cs, ProjectK/Assets/Scripts/UI/PlayerUI/PlayerUIManager.cs
[[Feature] 드롭박스 UI를 로컬에서만 열기]
1. 드롭박스 프리팹에 콜라이더 추가
2. 드롭박스.cs 에 이벤트 nullable 추가
3. InteractDropBox 함수에 IsOwner 조건문 추가
4. 플레이어UI매니저.cs OnOpenDropBox 함수를 이벤트에 등록
[[Feature] AddDroxBoxItemRpc에 받아온 아이템 id로 아이템 값을 가지고와서 haveItems에 저장]
[[Feature] 드롭박스 내용물 동기화]
1. 아이템 ID와 수량 동기화
2. 드롭박스 프리팹, 게임매니저 프리팹 수정
3. GameManager.cs 에 드롭박스 위치 배정하면 그위치에 전부 드롭박스 생성 추가
https://github.com/user-attachments/assets/bb094859-5c14-44e9-8a08-5d559c9c1ebc
=> net 드롭박스 뽑기 할 때 내용물 동기화

ProjectK/Assets/Scripts/GameManager/GameManager.cs, ProjectK/Assets/Scripts/Player/PlayerController.cs
[[Feature] 게임매니저 시작함수 정리]
1. 드롭박스 스폰, 캐릭터 스폰지역 배정 함수 이동
2. 케릭터 넘버로 플레이어 찾는 함수 추가
[[Update] 케릭터 넘버 동기화]
1. 네트워크변수화
=> 151 net 게임매니저에서 게임 시작 관리

ProjectK/Assets/Scripts/DropBox/DropBox.cs, ProjectK/Assets/Scripts/GameManager/GameManager.cs, ProjectK/Assets/Scripts/Player/PlayerController.cs
1. 플레이어가 박스 열때 자기 넘버 전달
2.  드롭박스에서 박스 여는 캐릭터 동기화
- 1. 열릴때 박스를 연 캐릭터Number를 저장
- openPlayerNumber
- 2. 아이템 선택시 서버로 선택된 slotIndex와 playerNumber를 전달
- 3. 서버에서 전달받은 playerNumber로 캐릭터를 찾은 후 itemPick 진행
=> 153 net13 드롭상자에서 아이템 습득시 요청한 캐릭터 인벤토리로 진행하기

ProjectK/Assets/DefaultNetworkPrefabs.asset, ProjectK/Assets/Prefabs/ThrowableItem.meta, ProjectK/Assets/Prefabs/ThrowableItem/Granade.prefab, ProjectK/Assets/Prefabs/ThrowableItem/Granade.prefab.meta, ProjectK/Assets/Prefabs/UI/PlayerUI.prefab, ProjectK/Assets/Scenes/MainScene.unity, ProjectK/Assets/Scripts/GameManager/GameManager.cs, ProjectK/Assets/Scripts/Item.meta, ProjectK/Assets/Scripts/Item/Granade.cs, ProjectK/Assets/Scripts/Item/Granade.cs.meta
1. Granade 프리팹 추가
2. Granade.cs 스크립트 추가
- 마우스 포인터 위치까지 날아가서 폭발함
- 생성된 뒤 5초 뒤에 항상 폭발
- 5m 범위안에 있는 모든 레이에 맞은 인스턴스에게 피해를 줌
https://github.com/user-attachments/assets/dc466f4e-7730-453f-83d3-52fa6413e830
=> [Add] Granade 프리팹 추가

ProjectK/Assets/Prefabs/UI/SystemUI.prefab, ProjectK/Assets/Scenes/GH.unity, ProjectK/Assets/Scripts/GameManager/GameManager.cs, ProjectK/Assets/Scripts/UI/SystemUI/SystemUIManager.cs, ProjectK/ProjectSettings/EditorBuildSettings.asset
1. systemUI 프리팹 LobbyPanel 관련 UI오브젝트 추가
2. LobbyPlayButton 버튼 클릭 시 SystemUIManager → GameManager.RequestStartGame() 호출
3. GameManager 내부에서 IsHost 판단 후 게임 시작 + SyncLobbyToGameTransitionRpc() 호출
4. SyncLobbyToGameTransitionRpc()에서 모든 클라이언트에 UI 전환 이벤트  전파
https://github.com/user-attachments/assets/084e3808-f710-4ffa-ae91-20af7e1c9ba7
=> [Feature] 게임 시작 UI패널 제작

ProjectK/Assets/Prefabs/UI/PlayerUI.prefab
[[Update] 크로스헤어 UI 레이케스트 오프]
1. UI 클릭시 크로스헤어 image가 클릭되어 UI에 반영이 안됨
=> 크로스헤어 레이케스트off

ProjectK/Assets/Prefabs/UI/SystemUI.prefab, ProjectK/Assets/Scenes/GH.unity, ProjectK/Assets/Scripts/UI/SystemUI/SystemUIManager.cs
1. 시스템UI 프리팹에 로그인 패널 추가
2. HostButton 버튼 클릭시 startHost 함수 호출
3. 인풋 필드에 접속할 아이피 입력 후Client Button을 누르면 startClient 호출
https://github.com/user-attachments/assets/147e81bc-cc51-4323-826c-e558a92cafa3
=> [Feature] 게임 접속 UI 구성

ProjectK/Assets/Prefabs/Effect/EffectSpawner.prefab, ProjectK/Assets/Prefabs/Effect/bloodEffect.prefab, ProjectK/Assets/Prefabs/PlayerNetwork.prefab, ProjectK/Assets/Scripts/Player/PlayerController.cs
1. 플레이어 프리팹에 파티클이 발생할 위치에 이펙트 스포너 프리팹 배치 및 추가
2. PlayerController.cs 에 EffectSpawner 변수 추가
3. TakeDamageRpc 함수에 PlayEffect함수 호출
https://github.com/user-attachments/assets/ad2153a6-5429-466c-8e51-f23095ba9ffc
=> [Feature] 플레이어 피격시 이펙트 추가 

ProjectK/Assets/Scripts/Player/PlayerController.cs, ProjectK/Assets/Scripts/Player/PlayerSight.cs
1. 사이즈변경 이벤트에 Owner만 구독
2. 컨틀로러에서 업데이트시 Owner인 경우에만 업데이트
=> [Feature] 크로스헤어 조정 소유권 정리

ProjectK/Assets/Scripts/InputManager/InputManager.cs
[캐릭터 안움직이기]
1. 게임매니저 스테이트 변화 구독
- Player로 바뀌었을때 All로 바꾸기
=> 191 게임 상태에 따른 플레이어 작동 상태 변경 및 동기화

ProjectK/Assets/Prefabs/Deployables item/WoodenBox.prefab, ProjectK/Assets/Prefabs/Effect/GrenadeExplosion.prefab, ProjectK/Assets/Prefabs/Effect/GrenadeExplosion.prefab.meta, ProjectK/Assets/Prefabs/ThrowableItem/Granade.prefab
이펙트 추가했지만, 수류탄이 터지면서 바로 사라지기에 확인할 수 없음.
=> [Add]수류탄 폭발 이펙트 추가

ProjectK/Assets/Scripts/Item/Granade.cs, ProjectK/Assets/Scripts/Sound/SoundObject.cs
[Update] 소리 재생 바깥에서 하기]
1. 재생 오브젝트를 부모에서 제외해서 생성
2. 돌아갈때 스포너가 있으면 다시 자식으로 들어감
=> 218 소리 오브젝트 해당 위치에 별개로 생성하기
